# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Feature Request
description: Suggest a new feature or improvement.
labels: ["triage"]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us evaluate your idea.
  
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Clearly describe what the feature is and the problem it solves.
      placeholder: Describe your feature idea and what problem it addresses.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution or Design
      description: Explain how you imagine this feature working. Include examples, diagrams, or pseudo-code if relevant.
      placeholder: Describe your proposed solution or design approach.
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact / Priority
      description: How important is this feature?
      options:
        - (P0)Critical – blocks existing use cases
        - (P1)High – significantly improves user experience
        - (P2)Medium – useful enhancement
        - (P3)Low – nice to have
      default: 2
    validations:
      required: true

  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the system does this feature relate to?
      multiple: true
      options:
        - Workflow Engine (Amber)
        - Workflow UI
        - Hub
        - Storage / Metadata
        - Deployment / Infrastructure
        - Other

  - type: markdown
    attributes:
      value: |
        By submitting this issue, you agree to follow the [Apache Code of Conduct](https://www.apache.org/foundation/policies/conduct).